# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170629_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('N', '선택 안 함'), ('F', '여성'), ('M', '남성')], default='N', max_length=1),
        ),
    ]
